FROM python:3.12 AS builder

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl pkg-config libssl-dev wget \
    && rm -rf /var/lib/apt/lists/*

# Install Rust (required to build the PyApp launcher)
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Download and unpack the latest PyApp source
WORKDIR /tmp
RUN curl -sSL https://github.com/ofek/pyapp/releases/latest/download/source.tar.gz -o pyapp-source.tar.gz \
    && tar -xzf pyapp-source.tar.gz \
    && mv pyapp-v* pyapp-latest


RUN rustup target add x86_64-pc-windows-gnu

RUN rustup target add x86_64-apple-darwin

# use cross for macos


ENV PYAPP_PROJECT_NAME=accli
ENV PYAPP_PROJECT_VERSION=1.0.3
ENV PYAPP_FULL_ISOLATION=1

# ENV CARGO_BUILD_TARGET="x86_64-pc-windows-gnu"
# ENV PYAPP_DISTRIBUTION_VARIANT_GIL=Windows

# Install PyApp from source
WORKDIR /tmp/pyapp-latest
